-- Criação da tabela 'vagas'
CREATE TABLE public.vagas (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    titulo TEXT NOT NULL,
    empresa TEXT NOT NULL,
    "desc" TEXT NOT NULL,
    categoria TEXT,
    local TEXT,
    tipo TEXT,
    contrato TEXT,
    salario TEXT,
    prazo TEXT,
    contacto TEXT,
    req TEXT,
    destaque BOOLEAN DEFAULT FALSE,
    publicado BOOLEAN DEFAULT TRUE,
    data TEXT
);

-- Habilitar a Segurança a Nível de Linha (Row Level Security - RLS)
ALTER TABLE public.vagas ENABLE ROW LEVEL SECURITY;

-- Política: Permitir que qualquer pessoa veja as vagas (Leitura / SELECT)
CREATE POLICY "Permitir leitura pública" 
ON public.vagas 
FOR SELECT 
TO public 
USING (true);

-- Política: Permitir inserção de novas vagas a partir da interface admin (Inserção / INSERT)
CREATE POLICY "Permitir inserções públicas" 
ON public.vagas 
FOR INSERT 
TO public 
WITH CHECK (true);

-- Política: Permitir atualização de vagas (Atualização / UPDATE)
CREATE POLICY "Permitir atualizações públicas" 
ON public.vagas 
FOR UPDATE 
TO public 
USING (true);

-- Política: Permitir a deleção de vagas (Deleção / DELETE)
CREATE POLICY "Permitir deleções públicas" 
ON public.vagas 
FOR DELETE 
TO public 
USING (true);
